
tasks:
  - before: pip3 install -r requirements.txt -r docs/requirements.txt pytest poetry; cd docs && make html ; cd ..
    command: python3 app.py
# Ports to expose on workspace startup (optional)
ports:
  - port: 5000
    onOpen: open-preview
github:
  prebuilds:
    addComment: true
vscode:
  extensions:
    - lextudio.restructuredtext
    - ms-python.python
